// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using getbiz_chat_app.Getbiz_DbContext;

namespace getbiz_chat_app.Migrations
{
    [DbContext(typeof(ChatBroadCastAppDB_DbContext))]
    [Migration("20220217130340_once")]
    partial class once
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("getbiz_chat_app.Models.chat_app_registration", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("about")
                        .HasColumnType("longtext");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("company_name")
                        .HasColumnType("longtext");

                    b.Property<string>("country_code")
                        .HasColumnType("longtext");

                    b.Property<string>("cust_id")
                        .HasColumnType("longtext");

                    b.Property<string>("designation")
                        .HasColumnType("longtext");

                    b.Property<string>("email_id")
                        .HasColumnType("longtext");

                    b.Property<string>("mobile_no")
                        .HasColumnType("longtext");

                    b.Property<string>("photo_id")
                        .HasColumnType("longtext");

                    b.Property<string>("share_link")
                        .HasColumnType("longtext");

                    b.Property<string>("user_blogs")
                        .HasColumnType("longtext");

                    b.Property<string>("user_name")
                        .HasColumnType("longtext");

                    b.HasKey("user_id");

                    b.ToTable("chat_app_registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
